import type { SupabaseClient } from "@supabase/supabase-js";
import { createHash } from "crypto";

/**
 * Referral helpers. The referral code itself is generated by a Postgres
 * trigger (migration 00061), so this module focuses on:
 *   - URL shape (kindar.com.br/r/CODE)
 *   - Click logging (anonymous, IP-hashed)
 *   - Stats queries
 *   - Reward crediting (called from Stripe webhook on first paid conv)
 */

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || "https://kindar.com.br";

export function buildReferralUrl(code: string): string {
  return `${APP_URL}/r/${code}`;
}

/** Hash IP into a short opaque token so we can dedupe clicks without
 *  storing personal data. 16 hex chars = 64 bits of entropy, plenty to
 *  tell duplicate visits apart without being reversible. */
export function hashIp(ip: string | null): string | null {
  if (!ip) return null;
  return createHash("sha256").update(ip).digest("hex").slice(0, 16);
}

export interface ReferralStats {
  code: string;
  totalClicks: number;
  totalSignups: number;
  totalRewards: number;
  monthsEarned: number;
  clickToSignupRate: number;
  signupToRewardRate: number;
}

export async function getReferralStats(
  supabase: SupabaseClient,
  userId: string
): Promise<ReferralStats | null> {
  const { data } = await supabase
    .from("v_referral_stats")
    .select(
      "referral_code, total_clicks, total_signups, total_rewards, months_earned"
    )
    .eq("user_id", userId)
    .maybeSingle();

  if (!data || !data.referral_code) return null;

  const clicks = data.total_clicks ?? 0;
  const signups = data.total_signups ?? 0;
  const rewards = data.total_rewards ?? 0;

  return {
    code: data.referral_code,
    totalClicks: clicks,
    totalSignups: signups,
    totalRewards: rewards,
    monthsEarned: data.months_earned ?? 0,
    clickToSignupRate: clicks > 0 ? signups / clicks : 0,
    signupToRewardRate: signups > 0 ? rewards / signups : 0,
  };
}
